FROM apache/airflow:2.9.3-python3.10

USER root

# Install system dependencies
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    gcc \
    && apt-get clean

USER airflow

# Copy requirements
COPY requirements.txt .

# Install only project dependencies (not full airflow stack)
RUN pip install --no-cache-dir \
    boto3 \
    pandas \
    pymysql \
    pycountry==26.2.16\
    sqlalchemy==1.4.46 \
    python-dotenv \
    mysql-connector-python

# Copy project
COPY . /opt/airflow/gov_data

# Copy DAG
COPY dags/ /opt/airflow/dags/